spring:
  application:
    name: message-management-system

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

redis:
  cache:
    default-timeout: 3600

proxy-api:
  url: https://api.proxyapi.ru/openai
  key: ${PROXY_API_KEY}
  model: gpt-4-turbo

naivebayes:
  dataset:
    filename: russian_words_labels.csv

maxentropy:
  dataset:
    filename: russian_words_labels.csv