spring:
  application:
    name: message-management-system

  data:
    redis:
      host: localhost
      port: 6379

redis:
  cache:
    default-timeout: 3600

proxy-api:
  url: https://api.proxyapi.ru/openai
  key:
  model: gpt-4-turbo