spring:
  application:
    name: message-management-system

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

redis:
  cache:
    default-timeout: 3600

proxy-api:
  url: https://api.proxyapi.ru/openai
  key: ${PROXY_API_KEY}
  model: gpt-4-turbo